apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: Editor
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'