apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: EditorWeb
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: Editor
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  namespace: web
  name: 368f7716-ccef-448e-b517-f47061b5bbd8