apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: EditorWeb
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: Editor
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  namespace: api
  name: 0b8b55c0-d4c9-4624-977a-a59ee9b94d5b